public class PantPrint extends javax.swing.JFrame {
    //Declara una variable del tipus "Calculadora".
    Calculadora calculadora = new Calculadora();
    
    
    /**
     * Creates new form PantPrint
     */
    public PantPrint() {
        initComponents();
        //Crea un objecte de tipus calculadora i el guarda a la vriable "calculadora".
        calculadora = new Calculadora();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton16 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButtonNum0 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButtonOpSum = new javax.swing.JButton();
        jButtonOpIgual = new javax.swing.JButton();
        jButtonNum4 = new javax.swing.JButton();
        jButtonNum3 = new javax.swing.JButton();
        jButtonNum2 = new javax.swing.JButton();
        jButtonOpMult = new javax.swing.JButton();
        jButtonNum1 = new javax.swing.JButton();
        jButtonNum6 = new javax.swing.JButton();
        jButtonNum5 = new javax.swing.JButton();
        jButtonNum8 = new javax.swing.JButton();
        jButtonNum7 = new javax.swing.JButton();
        jButtonNum9 = new javax.swing.JButton();
        jButtonOpRest = new javax.swing.JButton();
        jButtonOpDiv = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();

        jButton16.setText("-");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jTextPane1.setEditable(false);
        jScrollPane1.setViewportView(jTextPane1);

        jButtonNum0.setText("0");
        jButtonNum0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonNum0MouseClicked(evt);
            }
        });

        jButton2.setText(",");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButtonOpSum.setText("+");
        jButtonOpSum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonOpSumMouseClicked(evt);
            }
        });

        jButtonOpIgual.setText("=");

        jButtonNum4.setText("4");
        jButtonNum4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonNum4MouseClicked(evt);
            }
        });

        jButtonNum3.setText("3");
        jButtonNum3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonNum3MouseClicked(evt);
            }
        });
        jButtonNum3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNum3ActionPerformed(evt);
            }
        });

        jButtonNum2.setText("2");
        jButtonNum2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonNum2MouseClicked(evt);
            }
        });
        jButtonNum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNum2ActionPerformed(evt);
            }
        });

        jButtonOpMult.setText("*");

        jButtonNum1.setText("1");
        jButtonNum1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonNum1MouseClicked(evt);
            }
        });
        jButtonNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNum1ActionPerformed(evt);
            }
        });

        jButtonNum6.setText("6");
        jButtonNum6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonNum6MouseClicked(evt);
            }
        });

        jButtonNum5.setText("5");
        jButtonNum5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonNum5MouseClicked(evt);
            }
        });

        jButtonNum8.setText("8");
        jButtonNum8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonNum8MouseClicked(evt);
            }
        });

        jButtonNum7.setText("7");
        jButtonNum7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonNum7MouseClicked(evt);
            }
        });

        jButtonNum9.setText("9");
        jButtonNum9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonNum9MouseClicked(evt);
            }
        });

        jButtonOpRest.setText("-");

        jButtonOpDiv.setText("/");

        jButton18.setText("CE");
        jButton18.setEnabled(false);

        jButton19.setText("C");
        jButton19.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonNum7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonNum8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonNum9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonOpDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton18)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonNum4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonNum5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonNum6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonOpMult, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonNum0, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonOpSum))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonNum1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonNum2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonNum3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonOpRest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonOpIgual, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNum8)
                    .addComponent(jButtonNum7)
                    .addComponent(jButtonNum9)
                    .addComponent(jButtonOpDiv)
                    .addComponent(jButton18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNum4)
                    .addComponent(jButtonNum5)
                    .addComponent(jButtonNum6)
                    .addComponent(jButtonOpMult)
                    .addComponent(jButton19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonNum2)
                            .addComponent(jButtonNum1)
                            .addComponent(jButtonNum3)
                            .addComponent(jButtonOpRest))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonNum0)
                            .addComponent(jButton2)
                            .addComponent(jButtonOpSum)))
                    .addComponent(jButtonOpIgual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNum3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNum3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNum3ActionPerformed

    private void jButtonNum1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNum1MouseClicked
        this.calculadora.ponerNum("1");
        //Poner que en la pantalla salga el número marcado.
    }//GEN-LAST:event_jButtonNum1MouseClicked

    private void jButtonNum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNum2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNum2ActionPerformed

    private void jButtonNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNum1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNum1ActionPerformed

    private void jButtonNum2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNum2MouseClicked
        this.calculadora.ponerNum("2");
        //Poner que en la pantalla salga el número marcado.
    }//GEN-LAST:event_jButtonNum2MouseClicked

    private void jButtonNum3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNum3MouseClicked
        this.calculadora.ponerNum("3");
        //Poner que en la pantalla salga el número marcado.
    }//GEN-LAST:event_jButtonNum3MouseClicked

    private void jButtonNum4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNum4MouseClicked
        this.calculadora.ponerNum("4");
        //Poner que en la pantalla salga el número marcado.
    }//GEN-LAST:event_jButtonNum4MouseClicked

    private void jButtonNum5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNum5MouseClicked
        this.calculadora.ponerNum("5");
        //Poner que en la pantalla salga el número marcado.
    }//GEN-LAST:event_jButtonNum5MouseClicked

    private void jButtonNum6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNum6MouseClicked
        this.calculadora.ponerNum("6");
        //Poner que en la pantalla salga el número marcado.
    }//GEN-LAST:event_jButtonNum6MouseClicked

    private void jButtonNum7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNum7MouseClicked
        this.calculadora.ponerNum("7");
        //Poner que en la pantalla salga el número marcado.
    }//GEN-LAST:event_jButtonNum7MouseClicked

    private void jButtonNum8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNum8MouseClicked
        this.calculadora.ponerNum("8");
        //Poner que en la pantalla salga el número marcado.
    }//GEN-LAST:event_jButtonNum8MouseClicked

    private void jButtonNum9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNum9MouseClicked
        this.calculadora.ponerNum("9");
        //Poner que en la pantalla salga el número marcado.
    }//GEN-LAST:event_jButtonNum9MouseClicked

    private void jButtonNum0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNum0MouseClicked
        this.calculadora.ponerNum("0");
        //Poner que en la pantalla salga el número marcado.
    }//GEN-LAST:event_jButtonNum0MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonOpSumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonOpSumMouseClicked
        
    }//GEN-LAST:event_jButtonOpSumMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantPrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantPrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantPrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantPrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantPrint().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonNum0;
    private javax.swing.JButton jButtonNum1;
    private javax.swing.JButton jButtonNum2;
    private javax.swing.JButton jButtonNum3;
    private javax.swing.JButton jButtonNum4;
    private javax.swing.JButton jButtonNum5;
    private javax.swing.JButton jButtonNum6;
    private javax.swing.JButton jButtonNum7;
    private javax.swing.JButton jButtonNum8;
    private javax.swing.JButton jButtonNum9;
    private javax.swing.JButton jButtonOpDiv;
    private javax.swing.JButton jButtonOpIgual;
    private javax.swing.JButton jButtonOpMult;
    private javax.swing.JButton jButtonOpRest;
    private javax.swing.JButton jButtonOpSum;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
