public class PantPrint extends javax.swing.JFrame {
    //Declara una variable del tipus "Calculadora".
    Calculadora calculadora = new Calculadora(this);
    
    
    /**
     * Creates new form PantPrint
     */
    public PantPrint() {
        initComponents();
        //Crea un objecte de tipus calculadora i el guarda a la vriable "calculadora".
        calculadora = new Calculadora(this);
        pantallaCalc1.setContentType("text/plain");
    }
    
    public void escribirPantallaCalc(String textoAEscribir){
        pantallaCalc1.setText(textoAEscribir);
    }
    public void teclasPorDefecto(){
        jButtonNum0.setEnabled(true);
        jButtonNum1.setEnabled(true);
        jButtonNum2.setEnabled(true);
        jButtonNum3.setEnabled(true);
        jButtonNum4.setEnabled(true);
        jButtonNum5.setEnabled(true);
        jButtonNum6.setEnabled(true);
        jButtonNum7.setEnabled(true);
        jButtonNum8.setEnabled(true);
        jButtonNum9.setEnabled(true);
        //jButtonDecimal.setEnabled(false);
        jButtonOpSum.setEnabled(false);
        jButtonOpRest.setEnabled(false);
        jButtonOpMult.setEnabled(false);
        jButtonOpDiv.setEnabled(false);
        jButtonOpIgual.setEnabled(false);
        //jButtonC.setEnabled(false);
    }
    public void resetearConfIVariablesApp(){
        //Resetea las variables de la aplicación (3 línias siguientes):
        calculadora = new Calculadora(this);
        teclasPorDefecto();
        escribirPantallaCalc("");
    }
    public void desbloquearTeclas(int opcion){
        switch(opcion){
            case 1:
                jButtonDecimal.setEnabled(true);
                jButtonOpSum.setEnabled(true);
                jButtonOpRest.setEnabled(true);
                jButtonOpMult.setEnabled(true);
                jButtonOpDiv.setEnabled(true);
                //jButtonC.setEnabled(true);
                break;
            case 2:
                jButtonDecimal.setEnabled(true);
                jButtonOpSum.setEnabled(true);
                jButtonOpRest.setEnabled(true);
                jButtonOpMult.setEnabled(true);
                jButtonOpDiv.setEnabled(true);
                jButtonOpIgual.setEnabled(true);
                //jButtonC.setEnabled(true);
                break;
            case 3:
                jButtonNum0.setEnabled(false);
                jButtonDecimal.setEnabled(false);
                jButtonNum1.setEnabled(false);
                jButtonNum2.setEnabled(false);
                jButtonNum3.setEnabled(false);
                jButtonNum4.setEnabled(false);
                jButtonNum5.setEnabled(false);
                jButtonNum6.setEnabled(false);
                jButtonNum7.setEnabled(false);
                jButtonNum8.setEnabled(false);
                jButtonNum9.setEnabled(false);
                jButtonDecimal.setEnabled(false);
                jButtonOpSum.setEnabled(false);
                jButtonOpRest.setEnabled(false);
                jButtonOpMult.setEnabled(false);
                jButtonOpDiv.setEnabled(false);
                jButtonOpIgual.setEnabled(false);
                //jButtonC.setEnabled(false);
                break;
            case 4:
                jButtonDecimal.setEnabled(false);
                jButtonOpSum.setEnabled(false);
                jButtonOpRest.setEnabled(false);
                jButtonOpMult.setEnabled(false);
                jButtonOpDiv.setEnabled(false);
                jButtonOpIgual.setEnabled(false);
                jButtonNum0.setEnabled(true);
                jButtonNum1.setEnabled(true);
                jButtonNum2.setEnabled(true);
                jButtonNum3.setEnabled(true);
                jButtonNum4.setEnabled(true);
                jButtonNum5.setEnabled(true);
                jButtonNum6.setEnabled(true);
                jButtonNum7.setEnabled(true);
                jButtonNum8.setEnabled(true);
                jButtonNum9.setEnabled(true);
                break;
            case 5:
                jButtonNum0.setEnabled(false);
                jButtonNum1.setEnabled(false);
                jButtonNum2.setEnabled(false);
                jButtonNum3.setEnabled(false);
                jButtonNum4.setEnabled(false);
                jButtonNum5.setEnabled(false);
                jButtonNum6.setEnabled(false);
                jButtonNum7.setEnabled(false);
                jButtonNum8.setEnabled(false);
                jButtonNum9.setEnabled(false);
                jButtonDecimal.setEnabled(true);
                jButtonOpSum.setEnabled(true);
                jButtonOpRest.setEnabled(true);
                jButtonOpMult.setEnabled(true);
                jButtonOpDiv.setEnabled(true);
                //jButtonC.setEnabled(true);
                break;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton16 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pantallaCalc1 = new javax.swing.JTextPane();
        jButtonNum0 = new javax.swing.JButton();
        jButtonDecimal = new javax.swing.JButton();
        jButtonOpSum = new javax.swing.JButton();
        jButtonOpIgual = new javax.swing.JButton();
        jButtonNum4 = new javax.swing.JButton();
        jButtonNum3 = new javax.swing.JButton();
        jButtonNum2 = new javax.swing.JButton();
        jButtonOpMult = new javax.swing.JButton();
        jButtonNum1 = new javax.swing.JButton();
        jButtonNum6 = new javax.swing.JButton();
        jButtonNum5 = new javax.swing.JButton();
        jButtonNum8 = new javax.swing.JButton();
        jButtonNum7 = new javax.swing.JButton();
        jButtonNum9 = new javax.swing.JButton();
        jButtonOpRest = new javax.swing.JButton();
        jButtonOpDiv = new javax.swing.JButton();
        jButtonCE = new javax.swing.JButton();
        jButtonC = new javax.swing.JButton();

        jButton16.setText("-");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        pantallaCalc1.setEditable(false);
        jScrollPane1.setViewportView(pantallaCalc1);

        jButtonNum0.setText("0");
        jButtonNum0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonNum0MouseClicked(evt);
            }
        });

        jButtonDecimal.setText(",");
        jButtonDecimal.setEnabled(false);
        jButtonDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDecimalActionPerformed(evt);
            }
        });

        jButtonOpSum.setText("+");
        jButtonOpSum.setEnabled(false);
        jButtonOpSum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonOpSumMouseClicked(evt);
            }
        });
        jButtonOpSum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpSumActionPerformed(evt);
            }
        });

        jButtonOpIgual.setText("=");
        jButtonOpIgual.setEnabled(false);
        jButtonOpIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpIgualActionPerformed(evt);
            }
        });

        jButtonNum4.setText("4");
        jButtonNum4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonNum4MouseClicked(evt);
            }
        });

        jButtonNum3.setText("3");
        jButtonNum3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonNum3MouseClicked(evt);
            }
        });

        jButtonNum2.setText("2");
        jButtonNum2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonNum2MouseClicked(evt);
            }
        });
        jButtonNum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNum2ActionPerformed(evt);
            }
        });

        jButtonOpMult.setText("*");
        jButtonOpMult.setEnabled(false);
        jButtonOpMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpMultActionPerformed(evt);
            }
        });

        jButtonNum1.setText("1");
        jButtonNum1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonNum1MouseClicked(evt);
            }
        });
        jButtonNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNum1ActionPerformed(evt);
            }
        });

        jButtonNum6.setText("6");
        jButtonNum6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonNum6MouseClicked(evt);
            }
        });

        jButtonNum5.setText("5");
        jButtonNum5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonNum5MouseClicked(evt);
            }
        });

        jButtonNum8.setText("8");
        jButtonNum8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonNum8MouseClicked(evt);
            }
        });

        jButtonNum7.setText("7");
        jButtonNum7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonNum7MouseClicked(evt);
            }
        });

        jButtonNum9.setText("9");
        jButtonNum9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonNum9MouseClicked(evt);
            }
        });

        jButtonOpRest.setText("-");
        jButtonOpRest.setEnabled(false);
        jButtonOpRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpRestActionPerformed(evt);
            }
        });

        jButtonOpDiv.setText("/");
        jButtonOpDiv.setEnabled(false);
        jButtonOpDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpDivActionPerformed(evt);
            }
        });

        jButtonCE.setText("CE");
        jButtonCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCEActionPerformed(evt);
            }
        });

        jButtonC.setText("C");
        jButtonC.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonNum7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonNum8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonNum9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonOpDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonNum4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonNum5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonNum6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonOpMult, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonNum0, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonOpSum))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonNum1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonNum2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonNum3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonOpRest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonOpIgual, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNum8)
                    .addComponent(jButtonNum7)
                    .addComponent(jButtonNum9)
                    .addComponent(jButtonOpDiv)
                    .addComponent(jButtonCE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNum4)
                    .addComponent(jButtonNum5)
                    .addComponent(jButtonNum6)
                    .addComponent(jButtonOpMult)
                    .addComponent(jButtonC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonNum2)
                            .addComponent(jButtonNum1)
                            .addComponent(jButtonNum3)
                            .addComponent(jButtonOpRest))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonNum0)
                            .addComponent(jButtonDecimal)
                            .addComponent(jButtonOpSum)))
                    .addComponent(jButtonOpIgual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNum1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNum1MouseClicked
        this.calculadora.ponerNum("1");
        //Poner que en la pantalla salga el número marcado.
    }//GEN-LAST:event_jButtonNum1MouseClicked

    private void jButtonNum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNum2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNum2ActionPerformed

    private void jButtonNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNum1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNum1ActionPerformed

    private void jButtonNum2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNum2MouseClicked
        this.calculadora.ponerNum("2");
        //Poner que en la pantalla salga el número marcado.
    }//GEN-LAST:event_jButtonNum2MouseClicked

    private void jButtonNum3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNum3MouseClicked
        this.calculadora.ponerNum("3");
        //Poner que en la pantalla salga el número marcado.
    }//GEN-LAST:event_jButtonNum3MouseClicked

    private void jButtonNum4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNum4MouseClicked
        this.calculadora.ponerNum("4");
        //Poner que en la pantalla salga el número marcado.
    }//GEN-LAST:event_jButtonNum4MouseClicked

    private void jButtonNum5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNum5MouseClicked
        this.calculadora.ponerNum("5");
        //Poner que en la pantalla salga el número marcado.
    }//GEN-LAST:event_jButtonNum5MouseClicked

    private void jButtonNum6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNum6MouseClicked
        this.calculadora.ponerNum("6");
        //Poner que en la pantalla salga el número marcado.
    }//GEN-LAST:event_jButtonNum6MouseClicked

    private void jButtonNum7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNum7MouseClicked
        this.calculadora.ponerNum("7");
        //Poner que en la pantalla salga el número marcado.
    }//GEN-LAST:event_jButtonNum7MouseClicked

    private void jButtonNum8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNum8MouseClicked
        this.calculadora.ponerNum("8");
        //Poner que en la pantalla salga el número marcado.
    }//GEN-LAST:event_jButtonNum8MouseClicked

    private void jButtonNum9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNum9MouseClicked
        this.calculadora.ponerNum("9");
        //Poner que en la pantalla salga el número marcado.
    }//GEN-LAST:event_jButtonNum9MouseClicked

    private void jButtonNum0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNum0MouseClicked
        this.calculadora.ponerNum("0");
        //Poner que en la pantalla salga el número marcado.
    }//GEN-LAST:event_jButtonNum0MouseClicked

    private void jButtonDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDecimalActionPerformed
        this.calculadora.ponerNum(".");
    }//GEN-LAST:event_jButtonDecimalActionPerformed

    private void jButtonOpSumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonOpSumMouseClicked
        
    }//GEN-LAST:event_jButtonOpSumMouseClicked

    private void jButtonOpSumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpSumActionPerformed
        calculadora.ponerOperador("+");
    }//GEN-LAST:event_jButtonOpSumActionPerformed

    private void jButtonOpRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpRestActionPerformed
        calculadora.ponerOperador("-");
    }//GEN-LAST:event_jButtonOpRestActionPerformed

    private void jButtonOpMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpMultActionPerformed
        calculadora.ponerOperador("*");
    }//GEN-LAST:event_jButtonOpMultActionPerformed

    private void jButtonOpDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpDivActionPerformed
        calculadora.ponerOperador("/");
    }//GEN-LAST:event_jButtonOpDivActionPerformed

    private void jButtonOpIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpIgualActionPerformed
        calculadora.ponerOperador("=");
    }//GEN-LAST:event_jButtonOpIgualActionPerformed

    private void jButtonCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCEActionPerformed
        resetearConfIVariablesApp();
    }//GEN-LAST:event_jButtonCEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantPrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantPrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantPrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantPrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantPrint().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButtonC;
    private javax.swing.JButton jButtonCE;
    private javax.swing.JButton jButtonDecimal;
    private javax.swing.JButton jButtonNum0;
    private javax.swing.JButton jButtonNum1;
    private javax.swing.JButton jButtonNum2;
    private javax.swing.JButton jButtonNum3;
    private javax.swing.JButton jButtonNum4;
    private javax.swing.JButton jButtonNum5;
    private javax.swing.JButton jButtonNum6;
    private javax.swing.JButton jButtonNum7;
    private javax.swing.JButton jButtonNum8;
    private javax.swing.JButton jButtonNum9;
    private javax.swing.JButton jButtonOpDiv;
    private javax.swing.JButton jButtonOpIgual;
    private javax.swing.JButton jButtonOpMult;
    private javax.swing.JButton jButtonOpRest;
    private javax.swing.JButton jButtonOpSum;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane pantallaCalc1;
    // End of variables declaration//GEN-END:variables
}
